### ISSUE TITLE
uncaught exception: stackPrefetch: batch failed for element: dicomImage0

### ISSUE THREAD

**Issue by leonardorame** [chafey/cornerstoneTools#104]
Hi, what does the error "uncaught exception: stackPrefetch: batch failed for element: dicomImage0" mean?, in my browser's develoer's tools -> network I don't see any 404 error when loading wado images.

**Comment by swederik** [comment]
Ugh... It sounds like the last batch of requests all failed for some reason. See:

https://github.com/chafey/cornerstoneTools/blob/master/src/stackTools/stackPrefetch.js#L202

You can try to use the errorLoadingHandler to log the errors to see what is happening. I need to get some time to get the latest changes to prefetching merged in so we can stop using the batch system (see #103).

**Comment by swederik** [comment]
Just merged #103 to replace the old batched prefetcher with the request pool manager. Closing since I don't think this can occur anymore.
