### ISSUE TITLE
All mouse buttons perform WW/WC in addition to pan and zoom

### ISSUE THREAD

**Issue by cfecteau** [chafey/cornerstoneTools#11]
I haven't got that far in my code but I suspect they just perform whatever button 1 action is select in addition to pan and zoom. Noted on IE11, Firefox 32, and Chrome.

**Comment by swederik** [comment]
Closing this issue since this behaviour no longer occurs (test for yourself at https://rawgit.com/chafey/cornerstoneTools/master/examples/allImageTools/index.html)
