### ISSUE TITLE
Requesting an API to tune pinch sensitivity

### ISSUE THREAD

**Issue by carlok** [chafey/cornerstoneTools#119]
Reference:
See https://groups.google.com/forum/#!topic/cornerstone-platform/U1JRmgzeiLU

I tried the "zoom (pinch)" at
https://rawgit.com/chafey/cornerstoneTools/master/examples/alltouchtools/index.html
but it moves too fast and the library doesn't provide a way to tune the pinch sensitivity.

**Comment by leonardorame** [comment]
What I see while pinching is a lag between the action and the final zoom, I suspect the zoom event is repeated many times while the user pinches the screen, Erik, what do you think, am I right?.

It looks like the zoom change must be called when the user stops pinching, and not while he is doing this.

**Comment by carlok** [comment]
Did you already merged the changes into master? Are they in a branch? Thanks.

**Comment by swederik** [comment]
No they haven't been merged yet as I am still up. They are in my fork in the touchPinch branch. There are some other touch/mobile features / fixes I want to include first.
