### ISSUE TITLE
BUG in freeHand and question regarding globalImageIdSpecificToolStateManager

### ISSUE THREAD

**Issue by carlok** [chafey/cornerstoneTools#122]
1) While probe has a control to avoid placing a ROI in a region out of the physical values ((x < 0 || y < 0 || x >= eventData.image.columns || y >= eventData.image.rows)) freeHand doesn't have such control... you can pan the DCM getting a "dark" area and then put a corner of the polygon there.

Thanks.

**Comment by swederik** [comment]
Hi Carlo,

Sorry for the long delay. I just fixed this in 6a742aa8e1a3599607ed24011ee13445929eba7b.

I'll close the issue now.

**Comment by carlok** [comment]
thank you so much: I'll check it out ASAP

On Wed, Dec 9, 2015 at 1:30 PM, Erik Ziegler <notifications@github.com>
wrote:

> Closed #122 <https://github.com/chafey/cornerstoneTools/issues/122>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chafey/cornerstoneTools/issues/122#event-486817276>.
>



-- 
Carlo Perassi - http://perassi.org/
