### ISSUE TITLE
Write text on Image

### ISSUE THREAD

**Issue by panchotiya** [chafey/cornerstoneTools#123]
1. I want to write some text on image
2. I want to save image after modification like measurement,highlight ,probe
3. Multiple highlight on image

 will you please help me out

thanks

**Comment by swederik** [comment]
1. Look at the cornerstoneTools.drawTextBox API. It is not a movable tool, but you can use it to draw text on an image if you need to. It's also easy to just place HTML elements on top of the image, if static text is what you're after

2. You can save an image using the cornerstoneTools.saveAs function. See https://rawgit.com/chafey/cornerstoneTools/master/examples/saveAs/index.html

If you mean save and restore state, see the Application State example:
https://rawgit.com/chafey/cornerstoneTools/master/examples/toolState/index.html

3. Multiple copies of the highlight tool are not yet supported, but we would welcome a PR with this feature. You can also check the rectangleRoi tool to see if that suits your use case.

Please direct general questions like this to the google group (https://groups.google.com/forum/#!forum/cornerstone-platform) so we can keep Github for defects/feature requests.

Hope that helps!
