### ISSUE TITLE
Consider adding stack scrollToIndex() function

### ISSUE THREAD

**Issue by chafey** [chafey/cornerstoneTools#134]
See discussing here:
https://groups.google.com/forum/#!topic/cornerstone-platform/xfCE9A3Dkbo

**Comment by swederik** [comment]
Isn't this the same as this function?

https://github.com/chafey/cornerstoneTools/blob/master/src/util/scrollToIndex.js

**Comment by chafey** [comment]
Yup thats it, my bad.  Closing
