### ISSUE TITLE
Label text of ellipse tool not positioned correctly

### ISSUE THREAD

**Issue by hardmaster92** [chafey/cornerstoneTools#137]
I'm not 100% sure but I think that the bug appears on images which don't have 1:1 resolution (for example 800x500, 733x888...). The problem is that the text appears too far away from the ellipse. See the attached images.
![ellipse_bug2](https://cloud.githubusercontent.com/assets/15238282/11972922/c4367efe-a95b-11e5-80ca-ae9fb63ef40c.jpg)
![ellipse_bug](https://cloud.githubusercontent.com/assets/15238282/11972900/65b5b96c-a95b-11e5-9772-c77f9612ce52.jpg)

The rectangle tool doesn't have this problem.
I have tried the ellipse on 512x512 images and it works just fine

**Comment by swederik** [comment]
Thanks for the report! I'll take a look.

**Comment by swederik** [comment]
I see what happened: I switched the drawTextBox function to canvas coordinates instead of image coordinates, but apparently never updated the other tools. Will fix that now...

**Comment by swederik** [comment]
Sorry for the delay. This is fixed now and the textbox is floating / draggable.

You can test it here: https://rawgit.com/chafey/cornerstoneTools/master/examples/allImageTools/index.html

**Comment by hardmaster92** [comment]
Now it works but the label sticks only to the right side of the ellipse, never to the left
