### ISSUE TITLE
Annotation tool text box works only on Google Chrome

### ISSUE THREAD

**Issue by hardmaster92** [chafey/cornerstoneTools#138]
I've tried it with IE and Firefox but it doesn't work. Only the arrow is drawn but the modal with the text box doesn't appear.
I get this error message in the console:
TypeError: dialog.get(...).showModal is not a function               (index.html:132:8)

**Comment by swederik** [comment]
Thanks for the report. It seems I forgot to register the dialogs with the dialog polyfill.

**Comment by zelle-github** [comment]
Unfortunately, the problem exists again. The same error occurs again with Firefox. With Chrome it's working fine.

**Comment by swederik** [comment]
Are you sure? The link above works fine for me in Firefox.

**Comment by zelle-github** [comment]
Yes. With Firefox I can create an annotation, meaning the text dialog appears. But I can not change the annotation because on a double click the change dialog does not appear with Firefox, only with Chrome.

**Comment by hardmaster92** [comment]
I can confirm that editting doesn't work on Firefox

**Comment by swederik** [comment]
I believe with the last commit @zelle-github has fixed this now!
