### ISSUE TITLE
Mouse Wheel stack scroll not working on IE 11 (and 10 probably)

### ISSUE THREAD

**Issue by hardmaster92** [chafey/cornerstoneTools#139]
I tried fixing it by changing line 39 like this:
var wheelDelta = e.wheelDelta || -e.detail || (e.originalEvent != undefined && - e.originalEvent.detail) || -e.deltaY;

It actually works but I'm not sure if it's the right way.

**Comment by swederik** [comment]
The demo here:

https://rawgit.com/chafey/cornerstoneTools/master/examples/stackScroll/index.html

seems to work fine for me on IE via Edge (through the open in IE button). Do you get a console error?

**Comment by hardmaster92** [comment]
I tried the demo again using IE 11 and still not working...

**Comment by hardmaster92** [comment]
It turns out that it works with the latest version. It's just the example that is not updated. It works in my implementation but it doesn't work in stack scroll example page.
