### ISSUE TITLE
Simple angle (touch) not working

### ISSUE THREAD

**Issue by hardmaster92** [chafey/cornerstoneTools#140]
Simple angle touch tool doesn't work. When I tough the viewport only the first point is drawn and nothing else happenes.

**Comment by swederik** [comment]
Thanks for the report. I just merged a branch I've been using for a while with various fixes for touch tools. Simple angle touch tool seems to work fine now. I will tag 0.7.9 once I get a chance to test everything properly.

**Comment by swederik** [comment]
Seems to be working for me on rawgit with an iPad mini. I'll close this now.
