### ISSUE TITLE
Length tool showing pixels only in mammography (MG)

### ISSUE THREAD

**Issue by hardmaster92** [chafey/cornerstoneTools#141]
Length tool doesn't show the length in mm but in pixels only. The issue is present in MG series only.
You can use [this image ](http://www34.zippyshare.com/v/t5Nq0HVa/file.html) for testing:

**Comment by swederik** [comment]
Thanks for the report.

This happens when the image doesn't have PixelSpacing set. I took a look at the metadata and it does have a field called ImagerPixelSpacing, which is what other viewers / libraries seem to fall back to. I guess we can do the same.

**Comment by leonardorame** [comment]
Hi Erik, I was looking for ways to solve this and found the place in lengthTool.js to fix it, but as you mentioned the imagerPixelSpacing must be accessed to do the calcultations.

The file cornerstoneTools/src/metaData.js seems to be the one in charge of the MetaData, but I coulnd't find where it is populating its internal data structure, can you give me some pointers about this?.

Leonardo.

**Comment by swederik** [comment]
Hi Leonardo,

You need to add a metadata provider explicitly. There is an example one here: 

https://github.com/chafey/cornerstoneTools/blob/master/examples/exampleMetaDataProvider.js

which is used in several of the examples (e.g. referenceLines, orientationMarkers).

Hope that helps!

Erik

**Comment by leonardorame** [comment]
Erik, are you sure?, I'm trying to add imagerPixelSpacing to the metaData Provider used in lengthTool.js, I'm not trying to use one for my app.

**Comment by swederik** [comment]
Ah I see. Actually in lengthTool.js it is pulling rowPixelSpacing and columnPixelSpacing from the image itself, which is probably reading it from the DICOM in the image loader instead of using a metadata provider.

This is a pattern we are replacing soon with Chris's latest WebWorkers changes. Even if you added imagerPixelSpacing to lengthTool now it wouldn't work because that property is not being added to the image object by the image loader.

**Comment by leonardorame** [comment]
Yes, that's why I couldn't find where in the metaData.js the reference to rowPixelSpacing and colPixelSpacing are declared.

Ok, so, to fix this I should fix metaData.js first, right?

**Comment by leonardorame** [comment]
Well, I found a way, but it is mandatory to have a metaData provider registered before using the lengthTool.

I'll show my code later today...

**Comment by leonardorame** [comment]
After thinking about this there are some ways to solve this:

1) Create an event like onSetText to delegate the length calculation and suffix to the caller (who has a metaData provider).
2) Inject the imagerPixelSpacing data to eventData.image.
3) There is an onImageRendered event to allow us to override the default method, but rewriting it is a little overkill.

**Comment by leonardorame** [comment]
Please add this before line 101 of lengthTool.js:

            var cst = cornerstoneTools.metaData;
            var rowPixelSpacing = cst.get('imagePlane', eventData.image.imageId).rowPixelSpacing;
            var colPixelSpacing = cst.get('imagePlane', eventData.image.imageId).colPixelSpacing;
            var dx = (data.handles.end.x - data.handles.start.x) * (rowPixelSpacing || 1);
            var dy = (data.handles.end.y - data.handles.start.y) * (colPixelSpacing || 1);

**Comment by hardmaster92** [comment]
@leonardorame  this fix seems to work for me. Thanks :)

**Comment by leonardorame** [comment]
Ok, I've created a PR for this: https://github.com/chafey/cornerstoneTools/pull/198
