### ISSUE TITLE
Draw outside the image

### ISSUE THREAD

**Issue by danielaromeo** [chafey/cornerstoneTools#142]
Is it possible to let the user draw in the black spaces outside the image? I mean, if an image is taller then larger, there are two black spaces to the left and to the right of the image, and I would like the user to be able to draw (a rectangle, an ellipse etc.) there.
Is there any option to do it or can you point me in the right direction to change the code in order to reach the goal? Is it also possible to align the image to the left instead of centering it in the viewer?
Thanks!

**Comment by swederik** [comment]
For the first question, you just need to edit the tool to set "allowedOutsideImage" to true for all of the tool's handles:

https://github.com/chafey/cornerstoneTools/search?utf8=%E2%9C%93&q=allowedOutsideImage&type=Code

For the second question, aligning the image to the left or right of the viewer, this is a bit tricky. I've done it once but it felt a bit hacky:

````javascript
// Find the left and right boundaries of the canvases in the document
var enabledElement = cornerstone.getEnabledElement(element);
var left = $(enabledElement.canvas).offset().left;
var right = left + enabledElement.canvas.width;
````

If you want to position the image to snap to the right side of the canvas:
````javascript
// Set X translation to Canvas max in image pixels - image width
// This places it on the right side of the screen
position = cornerstone.pageToPixel(element, right, 0);
enabledElement.viewport.translation.x = position.x - enabledElement.image.width;
cornerstone.setViewport(element, enabledElement.viewport);
````

Or to the left side:
````javascript
// Use pageToPixel to and jQuery to find pixel coordinates of leftmost
// side of the current canvas
position = cornerstone.pageToPixel(element, left, 0);
enabledElement.viewport.translation.x = position.x;
cornerstone.setViewport(element, enabledElement.viewport);
````

**Comment by danielaromeo** [comment]
Thank you!
I updated the "cornestoneTools.js" file to the latest version and I noticed that the parameter "allowedOutsideImage" was already set to true for every tool that support it, including the Elliptical tool, but when I try to draw outside the image it still doesn't work.
Please find attached the screenshot of my viewer, can I draw where I put the green arrows using that parameter?
Thanks!

**Comment by swederik** [comment]
Yes I understand the question, but it seems you didn't understand my earlier answer. As I stated above, the allowedOutsideImage flag is set on the tool's **handles**, not on the tool itself. If you look at the search result I posted, you can see that the tools create measurements with measurement data that looks something like this:

````javascript
var measurementData = {
    visible: true,
    active: true,
    invalidated: true,
    handles: {
        start: {
            x: mouseEventData.currentPoints.image.x,
            y: mouseEventData.currentPoints.image.y,
            highlight: true,
            active: false
        },
        end: {
            x: mouseEventData.currentPoints.image.x,
            y: mouseEventData.currentPoints.image.y,
            highlight: true,
            active: true
        },
        textBox: {
            active: false,
            hasMoved: false,
            movesIndependently: false,
            drawnIndependently: true,
            allowedOutsideImage: true,
            hasBoundingBox: true
        }
    }
};
````

You can see that by default, the only **handle** that is allowed to be drawn outside the image is the textbox associated to the tool. If you add this same flag to the other handles, they too can be drawn outside the image.

Hope that helps!

**Comment by danielaromeo** [comment]
Thanks for your patience, yes, I didn't understand.
I added it to the other handles and it worked like a charm!
I'll try to align the image to the left then. Thanks again for all your help!
