### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by danielaromeo** [chafey/cornerstoneTools#143]
I would like to add a "Reset" button, to remove all the drawings and modifications made by the user to the image. I looked at the code and I have found "disable" and "deactivate" functions only, but they don't work. When I select again one of the tools used, the drawings appear again.
Is there a method I can use to reset everything?
Thanks!

**Comment by swederik** [comment]
Hi Daniel,

You can try looking at the tool management example:

https://rawgit.com/chafey/cornerstoneTools/master/examples/clearToolData/index.html

**Comment by danielaromeo** [comment]
Thank you Erik! I didn't notice this sample!
