### ISSUE TITLE
Framerate will not change once it has been set for the first time

### ISSUE THREAD

**Issue by tlacaelelrl** [chafey/cornerstoneTools#146]
At line 
`
if (!playClipToolData || !playClipToolData.data || !playClipToolData.data.length) {
            playClipData = {
                intervalId: undefined,
                framesPerSecond: framesPerSecond || 30,
                lastFrameTimeStamp: undefined,
                frameRate: 0,
                loop: true
            };
            cornerstoneTools.addToolState(element, toolType, playClipData);
        } else {
            playClipData = playClipToolData.data[0];
        }
		
        // if already playing, do not set a new interval
        if (playClipData.intervalId !== undefined) {
          
`

When playClipData has already been defined then the framesPerSecond are not set even when passing them to the function, for me this was the fix:

`
if (!playClipToolData || !playClipToolData.data || !playClipToolData.data.length) {
            playClipData = {
                intervalId: undefined,
                framesPerSecond: framesPerSecond || 30,
                lastFrameTimeStamp: undefined,
                frameRate: 0,
                loop: true
            };
            cornerstoneTools.addToolState(element, toolType, playClipData);
        } else {
            playClipData = playClipToolData.data[0];
        }
	playClipData.framesPerSecond = framesPerSecond || 30;	
        // if already playing, do not set a new interval
        if (playClipData.intervalId !== undefined) {
          
`

Thank you the great work!!

**Comment by swederik** [comment]
Whoops sorry about that. I was trying to fix something else and accidentally introduced this bug. Should be fixed now.

**Comment by tlacaelelrl** [comment]
Thank you for the great work.
