### ISSUE TITLE
Is XA series scroll/play possible?

### ISSUE THREAD

**Issue by hardmaster92** [chafey/cornerstoneTools#149]
I'll give some example:
XA: http://www10.zippyshare.com/v/nWCO5swL/file.html
XA series are collection of frames in a single dcm file and dicom viewers should be able to scroll or play these series. I see that cornerstone doesn't support this yet, it just loads the first image and it's done. Is it possible to be done?

**Comment by swederik** [comment]
Hi Stefan,

We do support that! Try adding ?frame=1 to your imageId.

**Comment by hardmaster92** [comment]
Yes, it really worked. Thanks a lot. 
But what about ES series. They are similar to XA but this method doesn't work for them.

**Comment by swederik** [comment]
I'm not sure, could you provide some sample files?

**Comment by hardmaster92** [comment]
Here's an [exapmle](http://www114.zippyshare.com/v/SYNm1wMF/file.html).
Thankfully the rar is small but the uncompressed file is 230 MB

**Comment by hardmaster92** [comment]
Since this issue is not ES related, I created [new one](https://github.com/chafey/cornerstoneTools/issues/150) . I will close this issue since it's resolved :)

**Comment by amitpanwar123** [comment]
I am unable to scroll XA images in cornerstone. Used URL like : Dicom//201712221750420360/Standered/1.2.840.114257.1.16356791.20175100.dcm?frame=2.Please provide me solution for that.

**Comment by dannyrb** [comment]
@amitpanwar123 can you create a new issue for your problem? I'm going to lock this thread as it's an older one, and broken functionality would be a _new_ problem.
