### ISSUE TITLE
Persistent tools

### ISSUE THREAD

**Issue by gokhandilek** [chafey/cornerstoneTools#157]
I was wondering what would be the strategy to persist the changes in the studies.
For example, if a measurement tool is used on an image, I want to save it. If this particular image is accessed again, I want to see the annotations.

**Comment by alatar-** [comment]
+1

**Comment by chafey** [comment]
Serialize the measurement data to JSON and save it with a reference to the imageId

**Comment by swederik** [comment]
Closing because Chris already answered this.

One example of saving and restoring state doing this can be found here:

https://rawgit.com/chafey/cornerstoneTools/master/examples/toolState/index.html
