### ISSUE TITLE
Color change on hover over handle doesn't work with Firefox

### ISSUE THREAD

**Issue by zelle-github** [chafey/cornerstoneTools#162]
With Chrome, if I hover with the mouse over a handle of a annotation, the annotation changes color from white to green and back to white if i move the mouse away from the handle. With Firefox the color changes to green and white very unpredictable. Sometimes more then one annotation is green and then all get white again and so on.

**Comment by lscoder** [comment]
`mouseMoveCallback` in `mouseButtonTool.js` is executed only when eventData.which is equal to zero but on Firefox and IE11 it's set to 1 when even if we aren't pressing any mouse button.

```
function mouseMoveCallback(e, eventData) {
    cornerstoneTools.toolCoordinates.setCoords(eventData);
    // if a mouse button is down, do nothing
    if (eventData.which !== 0) {
        return;
    }
    // ...
}
```

**Comment by swederik** [comment]
Is e.buttons supported everywhere? It seems to say Safari doesn't support it here: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons

If it's supported everywhere then yeah we should move to it.

**Comment by swederik** [comment]
This was addressed here: https://github.com/chafey/cornerstoneTools/pull/230
