### ISSUE TITLE
Draw horizontal and vertical lines

### ISSUE THREAD

**Issue by gokhandilek** [chafey/cornerstoneTools#165]
I was just wondering if it would be possible to draw vertical and horizontal lines on images?

**Comment by swederik** [comment]
For what purpose? As a tool? You can take a look at how we render reference lines here: https://github.com/chafey/cornerstoneTools/blob/547f29123bfc59e54a7a7c4734a09e7aee9fe2cb/src/referenceLines/renderActiveReferenceLine.js#L52

**Comment by gokhandilek** [comment]
Yes as a tool.
I can use the lines measurement tool but I need to estimate to see if the line is vertical or not.

**Comment by dannyrb** [comment]
@gokhandilek do you still have a need for this? @swederik is this a common radiologist tool? Or can we close this issue?

**Comment by dannyrb** [comment]
This is from almost a year ago, and not a common tool I've heard of or seen before. Moving to closed for now. If someone speaks up, we can open this and mark it up for grabs.

**Comment by Loverz55** [comment]
How to use it for the new version ?https://github.com/chafey/cornerstoneTools/blob/547f29123bfc59e54a7a7c4734a09e7aee9fe2cb/src/referenceLines/renderActiveReferenceLine.js#L52
