### ISSUE TITLE
Very slow showing images when scrolling in Chrome

### ISSUE THREAD

**Issue by atutka** [chafey/cornerstoneTools#168]
I have gwt component which wraps cornerstone and cornertoneTools. I encounter problem with very slow(delays) showing new image in stack when scrolling in Chrome(Firefox works nice). The weird part it is that when I added "overflow: scroll" to div in which is canvas, scrolling images was was working ok, with no delays. Another weird thing was when scroll delay occured when I clicked left mouse button image showed in instant. I think the problem is with mouseWheelEvent. Could it be that Chrome first call native browser event to scroll whole page and the second is event for scroll image?? Could you look into it, because I don't know if it cornerstoneTools bug or just my component unsual behaviour. I attached library with quick fix after some investigation I done in code.

Edit:
Chrome v. 54.0.2840.59 m (64-bit)
cornerntoneTools 0.7.9

[cornerstoneTools_with_fix.zip](https://github.com/chafey/cornerstoneTools/files/544121/cornerstoneTools_with_fix.zip)

**Comment by swederik** [comment]
Hi there,

We have also been experiencing similar issues. I have a small fix that is being tested currently, but I think it's orthogonal to the overflow CSS property. You shouldn't need any overflow property for the DIV which is enabled by Cornerstone. I'll post again when I've committed the other fix, in case that helps.

**Comment by freund17** [comment]
I had the same issue. Scrolling in a stack with stackScroll/stackScrollTouchDrag was fine but stackScrollWheel wasn't working at all - or only with great delays between frames. Also many scroll events got dropped. (All tested in chrome only)

Reverting the changes done in:
https://github.com/chafey/cornerstoneTools/commit/6838977bd10b603913e3cbf648695ed0a7eab452
fixed it for me though I dont exactly know why. I understand why the dropping of events got fixed. I do not understand why it fixed the delay problem. (Which should have been a delay of one frame after you stopped scrolling)
I also tested in the current version of edge (which was the reason this got added; but you know that), but i saw no problems / double events there.

**Comment by swederik** [comment]
Is this any better now?

**Comment by swederik** [comment]
I believe this has been fixed with requestAnimationFrame and some changes for scroll wheel handling. I'm going to close the issue. Reopen it if you are still having problems.

**Comment by amitpanwar123** [comment]
I am unable to scroll XA images in cornerstone. Used URL like : Dicom//201712221750420360/Standered/1.2.840.114257.1.16356791.20175100.dcm?frame=2

**Comment by amitpanwar123** [comment]
Sorry sir, for that can you provide me solution link for that.

**Comment by chafey** [comment]
I cannot without more information as I requested above.
