### ISSUE TITLE
Touch drag tools position issue

### ISSUE THREAD

**Issue by hardmaster92** [chafey/cornerstoneTools#170]
Probably I'm not the only one who noticed this. When you use tools on touch screen devices, the start/end points of the tool are not positioned where your finger is but slightly above it (if I remember corectly). Was it made that way on purpose or is it an issue?

**Comment by swederik** [comment]
That was on purpose, actually. It's easier to position the handles where you want them if you can see the handles (e.g. for measurements).

**Comment by hardmaster92** [comment]
Thanks for clearing this out, it actually makes sense :)
