### ISSUE TITLE
Coloring tool

### ISSUE THREAD

**Issue by danielaromeo** [chafey/cornerstoneTools#175]
Hello, is there a tool to view images with colors, like in the following image?
http://jimbodicomviewer.com/Manual%201.0/HowtoreadaDICOMdataset/images/image03.png
I can't find it in the Cornerstone Tools.

Thank you!

**Comment by swederik** [comment]
Hi Daniel,

Yes false color mapping is coming, but it will be in the core Cornerstone repository. It won't be here. I'm going to close this issue, but you can watch this PR: https://github.com/chafey/cornerstone/pull/107 to see when that feature is integrated.

Hope that helps!
