### ISSUE TITLE
All Image Tools Example Does not Update WW/WC or Zoom Text

### ISSUE THREAD

**Issue by cancan101** [chafey/cornerstoneTools#19]
When changing WW, WC or zooming in on the [All Image Tools Example](http://rawgit.com/chafey/cornerstoneTools/master/examples/allImageTools/index.html), the caption text is not changing. 

It seems that `onViewportUpdated` is not being called.

**Comment by cancan101** [comment]
@swederik Is this fixed?

**Comment by swederik** [comment]
Yep, this can be closed
