### ISSUE TITLE
highlight does not use the correct width / height for drawing background rect

### ISSUE THREAD

**Issue by cancan101** [chafey/cornerstoneTools#20]
This is related to / explanation for:
https://github.com/chafey/cornerstone/issues/16#issue-65320330

See:
http://stackoverflow.com/a/6722031/2638485

but basically this call is not correct if `scale != 1`:
```
context.rect(0, 0, context.canvas.clientWidth, context.canvas.clientHeight);
```
which it likely won't be after `setToPixelCoordinateSystem`.

**Comment by swederik** [comment]
The example now appears broken. See:

https://rawgit.com/chafey/cornerstoneTools/master/examples/highlight/index.html

![screenshot 2015-04-13 13 34 16](https://cloud.githubusercontent.com/assets/607793/7114834/d2e6a09c-e1e1-11e4-9b05-2861f8a5b88e.png)

**Comment by cancan101** [comment]
https://github.com/chafey/cornerstoneTools/pull/21#issuecomment-90961232

**Comment by chafey** [comment]
Reopening - looks like I messed up the merge - can someone submit a new pull request with the fix?

**Comment by cancan101** [comment]
@chafey PR pushed

**Comment by swederik** [comment]
#33 Fixes this
