### ISSUE TITLE
stackScrollKeyboard is not working in version v0.8.6

### ISSUE THREAD

**Issue by franjaviersans** [chafey/cornerstoneTools#208]
The keyboard input is not working for stack scrolling in this version. Even the example at  https://rawgit.com/chafey/cornerstoneTools/master/examples/stackScrollKeyboard/index.html does not work correctly.

Nevertheless, at least in version v0.8.1 all was working fine (https://rawgit.com/chafey/cornerstoneTools/dev/examples/stackScrollKeyboard/index.html).

The input get correctly into the function `keyPress`, but the `scroll` function has no effect. I think that the problem is that in the stackScroll.js you have to include that function with `import scroll from '../util/scroll';`

**Comment by swederik** [comment]
That's for the report!
