### ISSUE TITLE
circular imports dependency

### ISSUE THREAD

**Issue by kofifus** [chafey/cornerstoneTools#215]
stackPrefetch.js has

import requestPoolManager from '../requestPool/requestPoolManager.js';

requestPoolManager.js has

import { getMaxSimultaneousRequests } from '../util/getMaxSimultaneousRequests.js';

getMaxSimultaneousRequests.js has 

import stackPrefetch from '../stackTools/stackPrefetch.js';

which again tries to import stackPrefetch.js

Somehow webpack digests that but chrome/firefox module features break.

How can this be resolved ?

**Comment by swederik** [comment]
Closed by #216
