### ISSUE TITLE
How to keey active when I click the rectangle or ellipse ?

### ISSUE THREAD

**Issue by xingbofeng** [chafey/cornerstoneTools#220]
First of all, thanks this tool which help our team to build our own project!

Now we have a problem.I draw a rectangle or ellipse on the image,then when the mousemove event happen and my mouse above the rectangle or ellipse, the rectangle or ellipse will be active.We want to remove the points which is at the lefttop and rightbootm when it is not active, when we reclick the rectangle or ellipse, the rectangle or ellipse will be active and the points show.

I had seen the code `src/inputSources/mouseInput.js`,213th line ~ 268th line, the function `Mousemove()`.you declare a object `startPoints`, which includes the information about the points.then at 226th line, you give the point to canvas.When I remove the 226th line, error will happen.

```javascript
  const startPoints = {
    page: cornerstoneMath.point.pageToPoint(e),
    image: cornerstone.pageToPixel(element, e.pageX, e.pageY),
    client: {
      x: e.clientX,
      y: e.clientY
    }
  };

  startPoints.canvas = cornerstone.pixelToCanvas(element, startPoints.image);
```

Can you give me some advice? thanks!

**Comment by dannyrb** [comment]
@xingbofeng I believe the "left top" and "right bottom" points you're talking about are the ROI's "handles". If that is the case, then you can find the logic that controls when the handles are drawn (and how they are drawn) here:

*Rectangle ROI:*
https://github.com/chafey/cornerstoneTools/blob/master/src/imageTools/rectangleRoi.js#L173-L189

*Ellipse ROI:*
https://github.com/chafey/cornerstoneTools/blob/master/src/imageTools/ellipticalRoi.js#L157-L173

There are a lot of ways to achieve the effect you want, but hopefully this gets you started. The data/coordinates for the handles need to remain for the tool to function, but the logic that determines when/if/how to draw them can changed without much worry.

**Comment by dannyrb** [comment]
@xingbofeng If I missed what you were trying to ask, maybe include an image and a larger code snippet? If this did help move things along for you, please let me know so I can close this issue.
