### ISSUE TITLE
[How to] About image stacks

### ISSUE THREAD

**Issue by Hulda4us** [chafey/cornerstoneTools#222]
How can a given measurement tool be applied to all images in a stack?

From cornerstone wiki:

A ROI measurement could store state in the stack specific scope if the measurement applied to an image stack. In this case, the ROI would continue to be visible as the user changed to different ImageIds within the stack.

It also means that a given measurement tool could be applied to all images in a stack (if so desired). For example, an elliptical ROI could be applied on one image in a stack and then automatically recalculate when changed to the next image

how could I apply the elliptical ROI to a stack of pictures and get the mean parameter from all of it?

**Comment by dannyrb** [comment]
You'll notice that in the `src` for a large number of the tools, they pull in a `stateManager` that allows them to define and scope the state of the tool. Most tools use the `imageIdSpecificStateManager.js` found here:

https://github.com/chafey/cornerstoneTools/blob/master/src/stateManagement/imageIdSpecificStateManager.js

However, there are two other state managers that have wider scopes. The:

- `timeSeriesSpecificStateManager.js`
    - https://github.com/chafey/cornerstoneTools/blob/master/src/stateManagement/timeSeriesSpecificStateManager.js
- ``stackSpecificStateManager.js`
    - https://github.com/chafey/cornerstoneTools/blob/master/src/stateManagement/stackSpecificStateManager.js

It might be worth looking at one or two tools to see how the create and render tool data. Then, using one of the state manager's that offers a wider scope, try implementing your own tool that adds tool data and renders something on each image in a time series or stack.

I'm not immediately aware of implementations that use either of these state managers, but other users may be.
