### ISSUE TITLE
multiple viewports tools overlaping 

### ISSUE THREAD

**Issue by tlacaelelrl** [chafey/cornerstoneTools#233]
I have implemented the cornerstone tools and have three different viewports, each one having its own set of buttons to enable/disable tools if I don't enable any tool all three viewports are independent but as soon as I use one tool anything I do on one viewport replicates onto the other two as if they were synchronized.

Is this a expected behavior? if so can it be disabled?
See below image

If I use any of the following tools the behavior happens only on the viewport selected zoom, ww/wc, pan so this seems to be related directly to cornerstone tools

![sample](https://user-images.githubusercontent.com/1902898/30301089-1061c64c-971e-11e7-95ff-27b886d1b254.png)

**Comment by tlacaelelrl** [comment]
Just saw this 

"If two different enabled elements displayed the same ImageId, it should show up on both. This is the most commonly desired behavior and is therefore the default for cornerstone."

Since I am testing I am actually loading the same image IDs however from the three viewports it will be possible that two of the viewports have the same image id but need to be worked separately, is there a way I can detach them?

**Comment by swederik** [comment]
Hi there,

Good question. I think this is possible but I've never tried. It sounds like a common-enough use case that we should probably add an Example for it though, so thanks for bringing it up.

I think you would need to create and use two imageId-specific tool state managers for each of the elements. They are probably both set to use the global imageId tool state manager, so they are both retrieving the same tool state (and displaying it). I've never tried this, though.

See https://github.com/chafey/cornerstoneTools/blob/9fcab266400e2040c628b4498f2b1668a5afb744/src/stateManagement/imageIdSpecificStateManager.js#L7

https://github.com/chafey/cornerstoneTools/blob/9fcab266400e2040c628b4498f2b1668a5afb744/src/stateManagement/toolState.js#L79

I guess you would use newImageIdSpecificToolStateManager twice to make two tool state managers and then setElementToolStateManager to set these tool state managers for each element. Then I think the tools would act independently. Could you give that a shot?

**Comment by tlacaelelrl** [comment]
That worked perfectly, here is how I initialize the element

`
			"_cornerStoneEnableElement": function(image_url, element){
				var o = this;
				var tools = $(element).closest(".interface_workarea").find(".interface_tools");
				tools.removeClass("hide");
				tools.data("element", element);
				cornerstone.enable(element);
				cornerstone.loadImage(image_url).then(function(image){
					cornerstone.displayImage(element, image);
					cornerstoneTools.mouseInput.enable(element);
					cornerstoneTools.mouseWheelInput.enable(element);
					cornerstoneTools.wwwc.activate(element, 1);
					cornerstoneTools.pan.activate(element, 2);
					cornerstoneTools.zoom.activate(element, 4);
					cornerstoneTools.zoomWheel.activate(element);
					cornerstoneTools.probe.enable(element);
					cornerstoneTools.length.enable(element);
					cornerstoneTools.ellipticalRoi.enable(element);
					cornerstoneTools.rectangleRoi.enable(element);
					cornerstoneTools.angle.enable(element);
					var toolStateManager = cornerstoneTools.newImageIdSpecificToolStateManager();
					cornerstoneTools.setElementToolStateManager(element, toolStateManager);
				});
			}`
