### ISSUE TITLE
Does the ReferenceLine tool work with CornerstoneWADOImageLoader latest?

### ISSUE THREAD

**Issue by dannyrb** [chafey/cornerstoneTools#242]
It looks like the reference lines tool requires the following metaData per image:

- frameOfReferenceUID
- rowCosines
- columnCosines
- imagePositionPatient

See: [Source Code](https://github.com/chafey/cornerstoneTools/blob/master/src/referenceLines/renderActiveReferenceLine.js#L20-L34)

I can see this metaData provided in the exampleMetaDataProvider [located here](https://github.com/chafey/cornerstoneTools/blob/master/examples/exampleMetaDataProvider.js#L23-L30).

What I can't seem to figure out is where this information is provided in the current `CornerstoneWADOImageLoader`.  

The `wadors` metaDataProvider, [found here](https://github.com/chafey/cornerstoneWADOImageLoader/blob/2b949ef45adf72edca59e99ff93dbd90b4f58565/src/imageLoader/wadors/metaData/metaDataProvider.js#L34-L42), only appears to provide `imagePositionPatient`. 

The `wadouri` metaDataProvider, [found here](https://github.com/chafey/cornerstoneWADOImageLoader/blob/2b949ef45adf72edca59e99ff93dbd90b4f58565/src/imageLoader/wadouri/metaData/metaDataProvider.js#L38-L47), has `imagePositionPatient` and `frameOfReferenceUID`, but I don't see the cosines data.

It's also worth noting that the tool looks for the data in `imagePlane` whereas each of these providers returns that data for `imagePlaneModule`.

It does look like the OHIF viewer's metaDataProvider has a working implementation, which can be [found here](https://github.com/OHIF/Viewers/blob/de5fe8d5346481c534234865f00c70f41403c31a/Packages/ohif-cornerstone/client/lib/classes/MetadataProvider.js#L249-L259).

----

I'm not sure of the best route, but I noticed this inconsistency while trying to get the tool working for myself. Hoping this issue will spurn some action to align these libraries, or at least provide some light to someone else that has gotten lost.

**Comment by dannyrb** [comment]
@swederik, I'm okay to PR the work to sync these different libraries. Just need a 👍 and maybe a little direction around what naming you'd prefer

**Comment by swederik** [comment]
Ah I see so it looks like they diverged at some point....

I think we started adding 'Module' to indicate that they were DICOM modules (e.g. http://dicom.nema.org/medical/dicom/2017b/output/chtml/part03/sect_C.7.6.2.html). Let's switch cornerstoneTools to use imagePlaneModule.

**Comment by dannyrb** [comment]
Sorry for the long wait. I realize I keep opening tickets and not creating PRs. Made one so we can close out this ticket. Look for another one in the `cornerstoneWADOImageLoader` library here soon.

**Comment by dannyrb** [comment]
@swederik , the portion of this issue that can be resolved in this repo have been merged. I'll close it. Please try to take a peak at the other PR against `cornerstoneWADOImageLoader`.
