### ISSUE TITLE
Moving Cornerstone to an Org, and creating better documentation

### ISSUE THREAD

**Issue by dannyrb** [chafey/cornerstoneTools#249]
@swederik, long term.. I would love to see `cornerstone`, `cornerstoneTools`, `WADOImageLoader`, `WebImageLoader`, etc. maintained within a GitHub organization. Part of the difficulty in fighting for its use within my company is that all the projects appear to be "owned" by a single person. It might be worth cementing their relationship to one another, and having a clearer distinction about what is currently maintained and under active development/contribution.

It would also be cool to have more (and more approachable) information around how each of these pieces work together, and how to contribute (either documentation, or your own implementation of.. Say a metaDataProvider)

I love these libraries, and I've learned a lot from working with them on a daily basis over the last 6-months, but I think they could be made much more accessible. I would like to contribute, but I think a larger conversation regarding how to better structure, maintain, and continue to grow these libraries needs to be had. Lots of ideas, and I'd love to talk and create some action items.

If you're interested, please let me know. If nothing else, I'd be happy to hear about the current state of things, and your thoughts/opinions over a digital coffee.

**Comment by dannyrb** [comment]
Thanks for the thumbs up, @swederik. Is this something you have time to talk about? What would be the best way to reach out? For migration to an org, are there other stakeholders that need to be involved?

**Comment by swederik** [comment]
Hi Danny,

Yes we planned to move them all to the OHIF (https://github.com/OHIF) organization but it just hasn't happened yet. @chafey is the main stakeholder, so in the end it is up to him.

I'd certainly be up for a digital coffee so feel free to drop me an email and we can find a time to chat!

**Comment by dannyrb** [comment]
I'm closing this issue -- We've got it pegged in https://github.com/chafey/cornerstoneTools/issues/255, and we had our digital ☕️ (:
