### ISSUE TITLE
Calling brush.deactivate() causes brush.onImageRendered to be used and draw green hover circle

### ISSUE THREAD

**Issue by millerjv** [chafey/cornerstoneTools#253]
A naive call to brush.deactivate() without ever calling brush.activate() causes brush.onImageRendered() to be called and draws the green hover circle that tracks mouse movements.

This occurs when I call a naive method to disable all the tools before enabling a specific tool.

**Comment by swederik** [comment]
Should be fine now. Thanks for the report!
