### ISSUE TITLE
External modules

### ISSUE THREAD

**Issue by kofifus** [chafey/cornerstoneTools#256]
Outstanding are 
  https://github.com/chafey/cornerstoneTools/pull/250
  https://github.com/chafey/cornerstone/pull/171 
  https://github.com/chafey/cornerstoneWADOImageLoader/pull/134

Can these please be merged or is there any issue with that ?

Also is there a good place for me to submit documentation on loading ES6 modules directly ?

Thx!

**Comment by swederik** [comment]
Just merged those three. For now you can create a page in the Wiki https://github.com/chafey/cornerstone/wiki for that documentation
