### ISSUE TITLE
Double loading of JQuery and Hammer

### ISSUE THREAD

**Issue by kofifus** [chafey/cornerstoneTools#257]
Consider this common case:

```
<script src="cornerstone.min.js"></script>
<script src="jquery-3.2.1.js"></script>
<script>
  $(...) // I need jquery here for something
</script> 

```

As far as I can tell, in this case jquery is loaded to memory twice - once directly and once bundled with cornerstone through the imports inside cornerstone. While this (probably) does not produce runtime bugs it is very wasteful in memory. Also you can end up with two different versions of Jquery.

(note that this problem was there also before the recent import/expprt changes for ES6 modules ..)

This can be solved easily by changing `import $ from 'jquery';` to `const $ = window.$;` in conrnerstone\src\externalModules.js (and etc in externalModules.js in cornerstoneTools & wado)

However [here](https://github.com/chafey/cornerstoneTools/pull/214) @adreyfus seems to have some problem which I don't understand with AMD modules when cornerstone is packaged without JQeury.

What is the way to solve this ?

**Comment by swederik** [comment]
This should be fixed now. You can inject them with https://github.com/chafey/cornerstoneTools/blob/master/changelog.md#version-100
