### ISSUE TITLE
SaveAs - JPG

### ISSUE THREAD

**Issue by agustingrigoriu** [chafey/cornerstoneTools#260]
Hello! Is there a way to save an image in .JPG instead .PNG with the "SaveAs" Tool or any similar?

**Comment by dannyrb** [comment]
You should be able to accomplish a save to formats other than `png` using native HTML5 Canvas APIs.

Specifically, check out this MDN documentation on HTML5 Canvas's `toDataURL()`: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

This appears to be what the "SaveAs" tool is using [under the hood here](https://github.com/chafey/cornerstoneTools/blob/da7a185763c5316ab0cd6929814eadc0beeb5cce/src/imageTools/saveAs.js#L16). By not supplying a value, it defaults to `png`.

If this has answered your question, please close this issue. If you think we should add support to the "SaveAs" tool for different formats, let me know and I can add the appropriate tags.

**Comment by swederik** [comment]
Merged in #266
