### ISSUE TITLE
Please provide example showing segmentationBrush with stackScroll

### ISSUE THREAD

**Issue by luckfamousa** [chafey/cornerstoneTools#263]
Simply adding "cornerstoneTools.brush.activate()" to the stackScroll example seems not to work.
Could you please provide an example that demonstrates how one would actually segment a volume (e.g. a tumor).

**Comment by swederik** [comment]
I added one here: https://rawgit.com/chafey/cornerstoneTools/master/examples/segmentationBrush/index.html

There are still some bugs to sort out though.

**Comment by luckfamousa** [comment]
Great, that works and looks clean & easy. I should have tried to add stack functionality to the brush example. I instead tried to add the brush functionality to the stackScroll example, which somehow did not work. Thank you very much!
