### ISSUE TITLE
Magnifier Tool

### ISSUE THREAD

**Issue by jagjotwadali** [chafey/cornerstoneTools#277]
Currently I am using DWV dicom viewer for viewing DICOM images but certain features are not available in it .

I need a magnifier glass in DWV .Is it possible to use magnify.js file of cornerstone in dwv .

Kindly help in this regard.

**Comment by swederik** [comment]
I doubt that is possible without significant effort. I think you will need to adapt it for use in DWV.

**Comment by jagjotwadali** [comment]
Thank you for your reply .I will try to integrate if possible .

I have one question more.There are various Magnify glass libraries freely available in JQUERY and Javascript but these are only for JPEG and Bmp images and these libraries require a full size image and a small size image both.
In you library magnify.js ,you are displaying a DICOM image as a thumbnail on the web page .I want to ask if you are also using the same concept of giving the path of a large size DICOM image to display the magnifying glass.

**Comment by swederik** [comment]
At the moment we are just pulling pixels from the underlying canvas and rendering it in the magnifying glass.

I would rather render just the sub-section of the high-resolution image into the magnifying glass canvas itself (as suggested here: https://github.com/chafey/cornerstoneTools/issues/182 and kindly linked to by @diego0020).
