### ISSUE TITLE
Wrong rows/columns obtaining mothod in imagePlaneModule after today's change

### ISSUE THREAD

**Issue by hardmaster92** [chafey/cornerstoneTools#292]
The method used now uses _getNumberValues (which gets an array of numbers, not a number) rather than basic dataSet.uint16 method like this:
rows: dataSet.uint16('x00280010'),
columns: dataSet.uint16('x00280011'),

This results in undefined rows and columns fields in the image plane data.

**Comment by swederik** [comment]
Whoops, sorry about that. Will fix that ASAP.

**Comment by hardmaster92** [comment]
I should have post this in the cornerstoneWADOLoader, not here but thanks for noticing :)

**Comment by swederik** [comment]
Closed this (on WADO Image Loader) here: https://github.com/chafey/cornerstoneWADOImageLoader/commit/d941eb430ab553d53a9135213a50895b3c42bd5b
