### ISSUE TITLE
Missing argument in .sub() method introduced after the latest changes

### ISSUE THREAD

**Issue by hardmaster92** [chafey/cornerstoneTools#293]
in  src/util/pointProjector.js   (row 8)

const point = patientPoint.clone().sub();

should be

const point = patientPoint.clone().sub(**imagePlane.imagePositionPatient**);

**Comment by swederik** [comment]
I have no idea what happened here. I had this line in the file, I even tested the reference line example. I guess I must have hit undo or something.

Sorry!
