### ISSUE TITLE
saveAs Tool

### ISSUE THREAD

**Issue by cancan101** [chafey/cornerstoneTools#31]
Some way of "saving" the transformed image to PNG, etc.

For example, see:
* http://stackoverflow.com/questions/11112321/how-to-save-canvas-as-png-image
* https://github.com/eligrey/FileSaver.js

**Comment by chafey** [comment]
Technically this should not be hard to do - can you propose a UI design for this?

**Comment by swederik** [comment]
Closing since #34 was merged
