### ISSUE TITLE
Grabbing the vertex point of the angle measurement tool "breaks the V"

### ISSUE THREAD

**Issue by cancan101** [chafey/cornerstoneTools#32]
Grabbing the vertex point of the angle measurement tool "breaks the V":
![image](https://cloud.githubusercontent.com/assets/51059/7509876/f50acff6-f44a-11e4-8076-2f75bb583321.png)

**Comment by chafey** [comment]
This behavior is by design as this tool is intended to support cobb angles.  I can see how this behavior is not always desired and am open to a PR that would allow the V not to be broken (either via an option or another tool entirely)

**Comment by swederik** [comment]
Closing since #67 was merged
