### ISSUE TITLE
Freehand ROI Tool

### ISSUE THREAD

**Issue by cancan101** [chafey/cornerstoneTools#35]
Already [in the "backlog"](https://github.com/chafey/cornerstoneTools/blob/900fdebbcb22b0c1b814482ac6d22ce5e5ad78cd/README.md#backlog), but I'm creating this ticket to track feature.

**Comment by swederik** [comment]
What kind of freehand drawing are you looking for?

I am a big fan of how OpenLayers does their drawing:

**Freehand**: http://openlayers.org/en/v3.5.0/examples/draw-features.html
**Polygon**: http://openlayers.org/en/v3.5.0/examples/snap.html

Maybe we could do something along those lines?

**Comment by cancan101** [comment]
Would you reopen ticket while we discuss?

**Comment by swederik** [comment]
Yeah I already did. Sorry clicked "Close and Comment" instead of just "Comment"

**Comment by cancan101** [comment]
Either / both of those tools from OpenLayers are perfect.

**Comment by swederik** [comment]
I made a first attempt at a tool. You can try it here:

https://rawgit.com/swederik/cornerstoneTools/freehand/examples/freehandRoi/index.html

It still needs snapping, placed tool modification, and the actual squiggly part of freehand drawing, but it's a start.

**Comment by swederik** [comment]
**Update:** Added squiggly part of freehand drawing. Hold **Shift** to draw freehand

![freehandroi](https://cloud.githubusercontent.com/assets/607793/7766163/bf9dd228-0066-11e5-903a-5ca43ac0fd6f.gif)
