### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by cancan101** [chafey/cornerstoneTools#43]
Already [in the "backlog"](https://github.com/chafey/cornerstoneTools/blob/900fdebbcb22b0c1b814482ac6d22ce5e5ad78cd/README.md#backlog), but I'm creating this ticket to track feature.

Annotations such as:
* text
* arrows
* circles

**Comment by swederik** [comment]
I'll be getting to these this week.

**Comment by swederik** [comment]
See #47 for text+arrow annotation. Circular annotations are covered already by the ellipseRoi tool, no?

**Comment by cancan101** [comment]
I guess the question is would it be useful to have an annotation tool for circles (and potentially rectangles) as well separate from the ROI tools. One thought would be to allow adding text to these annotations like you have for the arrow tool. This raises the question however whether we want to merge those two ideas and allow adding text annotations to the ROI tools.
