### ISSUE TITLE
Measurement Events Not Working in Internet Explorer

### ISSUE THREAD

**Issue by Rionmonster** [chafey/cornerstoneTools#55]
I've been working on developing a very basic DICOM viewer that restyles and extends the existing CornerstoneDemo project recently and seemed to have encountered an issue with IE compatibility.

I'm using the latest version of [CornerstoneTools](https://github.com/chafey/cornerstoneTools) (0.6.2), the latest version of [Cornerstone.js](https://github.com/chafey/cornerstone) (0.7.7) and for the most part all of the tools have been working as expected (similar to the [All Image Tools example](https://rawgit.com/chafey/cornerstoneTools/master/examples/allImageTools/index.html)) with the exception of Internet Explorer, where the measurement events (e.g. Length, Angle, etc.) do not appear to work at all.

The previously mentioned All Image Tools example has them working just as you might expect within Internet Explorer, but when using an approach similar to the [CornerstoneDemo](http://chafey.github.io/cornerstoneDemo/), you'll notice that functions like Length and Angle do not get picked up for it.

The code for each is roughly the same : 

#### Working All Image Tools Example

```
// Define the element (equivalent to the Viewport and contains the <canvas> element)
var element = $('#dicomImage').get(0);

// Event handlers and other code (omitted for brevity)
    
// Code to enable the length tool
$('#enableLength').click(function() {
            activate('#enableLength')
            disableAllTools();
            cornerstoneTools.length.activate(element, 1);
});
```
#### Project Example (Doesn't work in Internet Explorer for Length or Angle)

```
// Length measurement
$('#length').on('click touchstart', function () {
        disableAllTools();
        // Test for a single viewport (targets the proper element, but none of the mouse events
        // are triggered after this executes
        cornerstoneTools.length.activate($('.viewport').get(0), 1);

        //forEachViewport(function (element) {
        //    cornerstoneTools.length.activate(element, 1);
        //});
});
```

I placed `debugger;` and `console.log(...)` calls throughout the inner functions to see if I could pick up on anything, but it's as if none of the mouse events at all are getting picked up within IE with Angle or Measurement selected.

Any ideas of something that I might be missing? I feel like it should be working (as it does in other browsers), but it may simply be my unfamiliarity with the project thus far that has caused me to miss something painfully obvious.

**Comment by RowanReid** [comment]
I've also been playing around and I think it has to do with this line:

```
cornerstoneTools.touchInput.enable(element);
```

Try commenting it out and see if those tools work in IE. At least that's a place to start.

**Comment by Rionmonster** [comment]
Well I'll be damned if that didn't work! It looks like that resolved the issue. Are there any side effects that are going to come with this (or perhaps just disabling touch events all together)?

**Comment by RowanReid** [comment]
I'm not sure of the side effects, as I only figured that fix out a day or two ago.  If you come across any please share!

**Comment by Rionmonster** [comment]
I didn't notice any additional side effects from this, however @swederik has a more recent pull request that integrates hammer.js into cornerstone and uses it to handle all of the touch-events, which works much better than the previous implementation.

You can read a bit more about some of the changes that were made in [this thread within the Google Groups page](https://groups.google.com/forum/#!topic/cornerstone-platform/ZNygNjMt7K0) and you can see [his current fork here](https://github.com/swederik/cornerstoneTools).

Closing this issue for now.
