### ISSUE TITLE
Continual Overlapping Tooling

### ISSUE THREAD

**Issue by Rionmonster** [chafey/cornerstoneTools#64]
With the latest build of [Erik's hammerjs branch of the repository](https://github.com/swederik/cornerstoneTools/tree/hammerjs), it appears to have some unexpected (at least in my mind) behaviors associated with it after the recent changes.

Many of the tools will appear to relate to one another after one event has stopped and another one has began (using the same tool) as seen below : 

![Tools Overlapping Issue](http://i.imgur.com/M5kui2U.gif)

As I mentioned previously, this only arose after using the latest cornerstoneTools changes with the hammerjs branch. The two may have some conflicting issues or may have simply not been ready to interact with one another as of yet, but I thought I would make the issue at least known.

**Comment by swederik** [comment]
That's odd, I haven't experienced that issue. Thanks for the report, I'll look into it.
This is using a mouse as a touch emulator, right?

**Comment by Rionmonster** [comment]
Yes, it's using the emulated touch events. 

I'll try testing it on an actual touch device shortly and see if I can put up an example to reproduce the issue.

**Comment by Rionmonster** [comment]
You can see a live example if you want to try to perform any testing on it below : 

[Cornerstone Tools with Touch Support; Latest Build](https://rawgit.com/Rionmonster/cornerstone-local-testing/master/Examples/TouchWithUpdatedTools.html)

**Comment by swederik** [comment]
Very weird... Thanks for posting the link.

**Comment by Rionmonster** [comment]
It appears that it actually doesn't just involve a single tool but all of the available tools as well : 

![Multiple Intersection of Tools](http://i.imgur.com/Xiv6fKA.gif)

I'll try taking a look at it shortly as I would guess that the "end" events for the tools aren't being properly triggered and they are just continuing, but it could be something quite a bit off from that.

**Comment by swederik** [comment]
Just fixed this. It was caused by a stupid typo, I changed touchendCallback to touchEndCallback but one instance didn't get replaced for some reason. Check the demo on #56

**Comment by Rionmonster** [comment]
I figured that it would be some minor issue. Glad to see that it's resolved. :)
