### ISSUE TITLE
Issue with reference line

### ISSUE THREAD

**Issue by idmpacs** [chafey/cornerstoneTools#66]
I am getting reference line at wrong position. Here is the screenshot.

![ref line](https://cloud.githubusercontent.com/assets/12911306/8205248/92cbda8c-150c-11e5-87df-1266ed78e539.png)

This is the case with all CT, MR studies I have.

**Comment by chafey** [comment]
Are you 100% certain you have not swapped row and column cosines in your metadata provider?

**Comment by idmpacs** [comment]
With earlier version of cornerstoneTools I was modifing following code

    // projects a patient point to an image point
    function projectPatientPointToImagePlane(patientPoint, imagePlane)
    {
        var point = patientPoint.clone().sub(imagePlane.imagePositionPatient);
        var x = imagePlane.columnCosines.dot(point) / imagePlane.columnPixelSpacing;
        var y = imagePlane.rowCosines.dot(point) / imagePlane.rowPixelSpacing;
        var imagePoint = {x: x, y: y};
        return imagePoint;
    }

    // projects an image point to a patient point
    function imagePointToPatientPoint(imagePoint, imagePlane)
    {
        var x = imagePlane.columnCosines.clone().multiplyScalar(imagePoint.x);
        x.multiplyScalar(imagePlane.columnPixelSpacing);
        var y = imagePlane.rowCosines.clone().multiplyScalar(imagePoint.y);
        y.multiplyScalar(imagePlane.rowPixelSpacing);
        var patientPoint = x.add(y);
        patientPoint.add(imagePlane.imagePositionPatient);
        return patientPoint;
    }

With below code

// projects a patient point to an image point
    function projectPatientPointToImagePlane(patientPoint, imagePlane)
    {
        var point = patientPoint.clone().sub(imagePlane.imagePositionPatient);
        var x = imagePlane.rowCosines.dot(point) / imagePlane.rowPixelSpacing;
        var y = imagePlane.columnCosines.dot(point) / imagePlane.columnPixelSpacing;
        var imagePoint = {x: x, y: y};
        return imagePoint;
    }

    // projects an image point to a patient point
    function imagePointToPatientPoint(imagePoint, imagePlane)
    {
        var y = imagePlane.columnCosines.clone().multiplyScalar(imagePoint.y);
        y.multiplyScalar(imagePlane.columnPixelSpacing);
        var x = imagePlane.rowCosines.clone().multiplyScalar(imagePoint.x);
        x.multiplyScalar(imagePlane.rowPixelSpacing);
        var patientPoint = x.add(y);
        patientPoint.add(imagePlane.imagePositionPatient);
        return patientPoint;
    }

After this I could get proper positions for reference lines. But now with either no change to the code or with modified code it is giving wrong results.

**Comment by idmpacs** [comment]
The values for Image orientation and image position are stored in the database
Here is the code.

//DICOM Tag 0020,0037
var imgOrt = imgDetails[0].ImageOrientation;
imgOrt = imgOrt.split(',');
var rowCos = new cornerstoneMath.Vector3(parseFloat(imgOrt[0]), parseFloat(imgOrt[1]), parseFloat(imgOrt[2]));
var colCos = new cornerstoneMath.Vector3(parseFloat(imgOrt[3]), parseFloat(imgOrt[4]), parseFloat(imgOrt[5]));

//DICOM Tag 0020,0032
var imgPos = imgDetails[0].ImagePosition;
imgPos = imgPos.split(',');
var pos = new cornerstoneMath.Vector3(parseFloat(imgPos[0]), parseFloat(imgPos[1]), parseFloat(imgPos[2]));

I tried swapping row and column cosines but result is not proper.

**Comment by chafey** [comment]
Ugh, I think the original code might have been right.  DICOM defines the first x,y,z in image orientation to be the direction of the first ROW which matches the X direction, not the Y.  @swederik did you make the change based on your MPR reformat code or based on original DICOM data?  If it was based on your MPR code, you may have swapped things accidently

**Comment by swederik** [comment]
Ugh indeed. No I wasn't using original DICOM data (was using volumetric data converted via ITK), so it is entirely possible that my previous "fix" actually broke point projection based on real DICOM image orientation tags. I just added a PR to revert the previous changes.

@idmpacs Which previous version do you mean? When did you pull? According to the commit history, apart from some small changes to use pixelToCanvas, nothing has changed in the repository related to reference lines for 4 months or so. Are you editing the src files and running grunt to rebuild the compiled version?

**Comment by idmpacs** [comment]
With latest update the reference line orientation is proper but the length of line and position is not correct. Also see in the video how ref line position is shifting while panning. This shift does not occur with other annotations on image panning. Any suggestions ?

![refline issue](https://cloud.githubusercontent.com/assets/12911306/8271963/9800cefe-184f-11e5-901c-80d3d0b810c0.gif)

**Comment by swederik** [comment]
Wow very bizarre. I'll take a look. Sorry I haven't had a chance to fix this yet.

**Comment by idmpacs** [comment]
The reason for the shift could be because those images are of different sizes. The left one is 512 x 230 and right one is 512 x 512. I can send you images, I don't know where.

**Comment by idmpacs** [comment]
It seems the problem is solved. I checked it on 5-6 studies and it is coming out fine.
Thanks.

**Comment by chafey** [comment]
Ahh this could be a bug specific to gantry tilt cases.  I took a "shortcut"
and calculate the intersection by projecting two corners instead of doing a
true plane/plane intersection.  A PR with a true plane/plane calculation
would be most welcome!
