### ISSUE TITLE
cornerstoneTools.mouseInput.enable() should check to make sure it isn't already enabled

### ISSUE THREAD

**Issue by chafey** [chafey/cornerstoneTools#89]
See this thread:
https://groups.google.com/forum/#!topic/cornerstone-platform/lcvUVzikNsE

We should handle this better - perhaps by preventing the handlers from being added if they are already on there, or at least a console warning.  Should also consider this for other enable()/disable() pairs too

**Comment by swederik** [comment]
Perhaps it's easiest to just do what we do for all the other enable / disable pairs? (Disable everything first, then enable the handlers again.)

**Comment by swederik** [comment]
Closing this, turns out I added a
```` javascript
disable(element)
````

call to mouseinput.enable already. 

See:
https://github.com/chafey/cornerstoneTools/blob/master/src/inputSources/mouseInput.js#L204
