### ISSUE TITLE
range function in src/stackTools/stackPrefetch.js endless.

### ISSUE THREAD

**Issue by Ethoxyethaan** [chafey/cornerstoneTools#90]
I was fiddling around and got my app locked up.

the range function needs assertions because it can end up in a long loop.

suggested patch:

    function range(lowEnd, highEnd) {
        // Javascript version of Python's range function
        // http://stackoverflow.com/questions/3895478/does-javascript-have-a-method-like-range-to-generate-an-array-based-on-suppl

        //don't allow undefined / null to be passed to this function.
        lowEnd = lowEnd||0;
        highEnd = highEnd||0;
        var arr = [],
            c = highEnd - lowEnd + 1;
        c=c>0?c:0;//lets not do this.
        while ( c-- ) {
            arr[c] = highEnd--;
        }
        return arr;
    }

**Comment by swederik** [comment]
Thanks! I'll fix it ASAP. Already planning to change stackPrefetch as mentioned here: https://groups.google.com/forum/#!topic/cornerstone-platform/q5vZ8tgVC4I
