### ISSUE TITLE
Show reference lines on

### ISSUE THREAD

**Issue by idmpacs** [chafey/cornerstoneTools#99]
Currently the reference lines are shown like this

![ref line](https://cloud.githubusercontent.com/assets/12911306/8875015/add04b8a-3233-11e5-953c-b485a2c3844a.png)

I want to show reference lines on all other viewers only related to the image user is interacting with like below screenshot.

![ref line 1](https://cloud.githubusercontent.com/assets/12911306/8875262/7c367e44-3235-11e5-93b0-a616a94107ca.png)

**Comment by chafey** [comment]
This is happening because the reference lines algorithm is not a true plane/plane intersection (it uses the simpler two corner approach).  Perhaps this is something you could contribute?

**Comment by swederik** [comment]
Plane/plane intersection is being addressed in #105. It sounds like the filed issue actually deals with selectively enabling/disabling the reference line tool.

If you want to hide reference lines for the element the user is interacting with, you'll need to store which viewport is "Active" somewhere, and then whenever the active viewport changes, disable reference lines for the new viewport.

You can use CornerstoneToolsMouseDown, CornerstoneToolsMouseClick, CornerstoneToolsMouseWheel, etc to set your active flag.

**Comment by swederik** [comment]
Closing since #105 was merged.
